name: Run Tests

on:
  push:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      - run: pip3 install -r requirements.txt
      - run: pytest tests